name: AndreaFarina

on:
  push:
    branches: [ "action-make" ]
  pull_request:
    branches: [ "action-make" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

   # - name: configure
   #   run: ./configure

    - name: Install dependencies
      run: sudo apt-get install -y software-properties-common
           sudo add-apt-repository -y ppa:graphics-drivers/ppa
           sudo apt-get update
           sudo apt-get install -y nvidia-cuda-toolkit
    
    - name: Install CUDA
      run: 
       # sudo apt-get install -y software-properties-common
       # sudo add-apt-repository -y ppa:graphics-drivers/ppa
       # sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit

    - name: Verify CUDA installation
      run: nvcc --version

    - name: Run make
      run: make

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-files
        path: ./ # Sostituisci con il percorso corretto
