name: AndreaFarina

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

   # - name: configure
   #   run: ./configure

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Run make
      run: make

   # - name: Run distcheck
    #  run: make distcheck
